name: movie_app
description: A Flutter movie application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.0.2
  provider: ^6.1.5+1
  # Removed sqflite, path_provider, path
  http: ^1.5.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#08051F"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#08051F"
    image: assets/images/logo.png